name: deploy-test
on: [push]
defaults:
  working-directory: /usr/local/eco-docker
jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
      - run: docker-compose down
      - run: docker-compose build --no-cache
      - run: docker-compose up -d --remove-orphans
